[package]
name = "interslavic-rs"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/gold-silver-copper/interslavic-rs"
[dependencies]
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
