[package]
name = "interslavic"
version = "0.1.3"
edition = "2021"
description = "interslavic utilities in rust "
license = "MIT OR Apache-2.0"

exclude = [
  "assets/*",
  ".github",
  "Makefile.toml",
  "CONTRIBUTING.md",
  "*.log",
  "tags",
]

[dependencies]
csv = "1.3.0"
serde = "1.0.197"
serde_derive = "1.0.197"


[dev-dependencies]


[[example]]
name = "slava"
doc-scrape-examples = true
